<?php
// module/Pegawai/view/pegawai/pegawai/add.phtml:

 $title = 'Add new Pegawai';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('pegawai', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nama'));
 echo $this->formRow($form->get('nip'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();