<?php
// module/Pegawai/view/pegawai/pegawai/index.phtml:

$title = 'Data Pegawai';
$this->headTitle($title);
$url_order = 'ASC';

if ($order_by == 'nama')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'nip')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
    <a href="<?php echo $this->url('pegawai', array('action'=>'add')); ?>">Add pegawai baru</a>
</p>

<table class="table">
     <tr>
         <th><a href="<?php echo $this->url('pegawai',array('order_by' => 'nama', 'order' => $url_order));?>">Nama</a></th>
         <th><a href="<?php echo $this->url('pegawai',array('order_by' => 'nip', 'order' => $url_order));?>">NIP</a></th>
         <th>&nbsp;</th>
     </tr>    
     <?php foreach ($this->paginator as $pegawai) : // <-- change here! ?>
         <tr>
             <td><?php echo $this->escapeHtml($pegawai->nama);?></td>
             <td><?php echo $this->escapeHtml($pegawai->nip);?></td>
             <td>
                 <a href="<?php echo $this->url('pegawai',
                     array('action' => 'edit', 'id' => $pegawai->id));?>">Edit</a>
                 <a href="<?php echo $this->url('pegawai',
                     array('action' => 'delete', 'id' => $pegawai->id));?>">Delete</a>
             </td>
         </tr>
     <?php endforeach; ?>
 </table>
                
 <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'pegawai'
     )
 );
 ?>