<?php
// module/Album/view/album/album/index.phtml:

$title = 'Data Pegawai';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
    <a href="<?php echo $this->url('pegawai', array('action'=>'add')); ?>">Add pegawai baru</a>
</p>

<table class="table">
    <tr>
        <th>Nama</th>
        <th>NIP</th>
        <th>Mail</th>
        <th>Jabatan</th>
        <th>Status</th>
        <th>Gender</th>
        <th>Jenjang Jabatan</th>
        <th>Sub Unit</th>
        <th>Unit</th>
        <th>&nbsp;</th>              
    </tr>
    
    <?php   
        $i = 0;
        $maxIteration = 10; 
        foreach ($pegawais as $pegawai) :  
    ?>
    
    <tr>
        <td><?php echo $this->escapeHtml($pegawai->nama);?></td>
        <td><?php echo $this->escapeHtml($pegawai->nip);?></td>
        <td><?php echo $this->escapeHtml($pegawai->mail);?></td>
        <td><?php echo $this->escapeHtml($pegawai->jabatan);?></td>
        <td><?php echo $this->escapeHtml($pegawai->status);?></td>
        <td><?php echo $this->escapeHtml($pegawai->gender);?></td>
        <td><?php echo $this->escapeHtml($pegawai->jenjang_jabatan);?></td>
        <td><?php echo $this->escapeHtml($pegawai->sub_unit);?></td>
        <td><?php echo $this->escapeHtml($pegawai->unit);?></td>
        <td>
            <a href="<?php echo $this->url('pegawai',array('action'=>'edit', 
                'id' => $pegawai->id)); ?>">Edit</a>
            <a href="<?php echo $this->url('pegawai',array('action'=>'delete', 
                'id' => $pegawai->id)); ?>">Delete</a>
        </td>
    </tr>
    <?php
        if ($i <= $maxIteration) {
            $i++;
        }
        else {
            break;
        }
        
        endforeach;
    ?>
</table>